export type Theme = {
  background: string;
  backgroundMuted: string;
  foreground: string;
  foregroundMuted: string;
  textColor: string;
  accentColor: string;
};

export const themes: Record<string, Theme> = {
  "orange spark": {
    background: "#FFFFFF",
    backgroundMuted: "#ECECEC",
    foreground: "#BEBEBE",
    foregroundMuted: "#FD4B27",
    textColor: "#000000",
    accentColor: "#FD4B27",
  },
  "standard light": {
    background: "#EEEEEE",
    backgroundMuted: "#DDDDDD",
    foreground: "#B2B2B2",
    foregroundMuted: "#444444",
    textColor: "#353535",
    accentColor: "#353535",
  },
  frost: {
    background: "#DAE0F5",
    backgroundMuted: "#C1C7DF",
    foreground: "#92A4BE",
    foregroundMuted: "#5A748A",
    textColor: "#485D71",
    accentColor: "#506477",
  },
  cappuccino: {
    background: "#D8D2C3",
    backgroundMuted: "#CDC0AF",
    foreground: "#8B6F5C",
    foregroundMuted: "#5D4737",
    textColor: "#393B3B",
    accentColor: "#513A2A",
  },
  verdant: {
    background: "#1F201B",
    backgroundMuted: "#272822",
    foreground: "#E0D88A",
    foregroundMuted: "#8DC027",
    textColor: "#E2E2DC",
    accentColor: "#8DC027",
  },
  "shadow blue": {
    background: "#0B0E13",
    backgroundMuted: "#141A24",
    foreground: "#394760",
    foregroundMuted: "#9FADC6",
    textColor: "#BDC9DF",
    accentColor: "#9FADC6",
  },
  "standard dark": {
    background: "#0e0e0e",
    backgroundMuted: "#161616",
    foreground: "#444444",
    foregroundMuted: "#b6b6b6",
    textColor: "#d9d9d9",
    accentColor: "#d9d9d9",
  },
  // "red black": {
  //   background: "#E3655B",
  //   backgroundMuted: "#E9847C",
  //   foreground: "#BA534B",
  //   foregroundMuted: "#FCFCFC",
  //   textColor: "#0D090A",
  //   accentColor: "#FCFCFC",
  // },
  // "crystal blue": {
  //   background: "#EBFCFF",
  //   backgroundMuted: "#C9F6FF",
  //   foreground: "#ADE8F4",
  //   foregroundMuted: "#06B7DA",
  //   textColor: "#06B7DA",
  //   accentColor: "#06B7DA",
  // },
  // ocean: {
  //   background: "#0096C7",
  //   backgroundMuted: "#25A9D4",
  //   foreground: "#66C0DD",
  //   foregroundMuted: "#ffffff",
  //   textColor: "#FFFFFF",
  //   accentColor: "#FFFFFF",
  // },
  // verdant: {
  //   background: "#208B3A",
  //   backgroundMuted: "#3DAA58",
  //   foreground: "#79B989",
  //   foregroundMuted: "#ffffff",
  //   textColor: "#FFFFFF",
  //   accentColor: "#FFFFFF",
  // },
  // wisteria: {
  //   background: "#8187DC",
  //   backgroundMuted: "#ADA7FF",
  //   foreground: "#B3B7EA",
  //   foregroundMuted: "#ffffff",
  //   textColor: "#FFFFFF",
  //   accentColor: "#f0e0ff",
  // },
  // "purple like": {
  //   background: "#3F3244",
  //   backgroundMuted: "#60495A",
  //   foreground: "#878387",
  //   foregroundMuted: "#F7FBF2",
  //   textColor: "#FFFFFF",
  //   accentColor: "#FFFFFF",
  // },
  // "forest haze": {
  //   background: "#354f52",
  //   backgroundMuted: "#2f3e46",
  //   foreground: "#52796f",
  //   foregroundMuted: "#84a98c",
  //   textColor: "#FFFFFF",
  //   accentColor: "#cad2c5",
  // },
  // "volcanic heat": {
  //   background: "#0b090a",
  //   backgroundMuted: "#161a1d",
  //   foreground: "#370617",
  //   foregroundMuted: "#9d0208",
  //   textColor: "#FFFFFF",
  //   accentColor: "#9d0208",
  // },
  // "sunset glow": {
  //   background: "#FFB347",
  //   backgroundMuted: "#FFD580",
  //   foreground: "#FF7F50",
  //   foregroundMuted: "#FF4500",
  //   textColor: "#4B1E00",
  //   accentColor: "#FF4500",
  // },
  // "misty morning": {
  //   background: "#D3E4CD",
  //   backgroundMuted: "#ADC2A9",
  //   foreground: "#A3B18A",
  //   foregroundMuted: "#6B705C",
  //   textColor: "#3E4235",
  //   accentColor: "#6B705C",
  // },
  // "arctic chill": {
  //   background: "#E0FBFC",
  //   backgroundMuted: "#C2DFE3",
  //   foreground: "#9DB4C0",
  //   foregroundMuted: "#5C6B73",
  //   textColor: "#293241",
  //   accentColor: "#5C6B73",
  // },
  // "desert dusk": {
  //   background: "#EDC9AF",
  //   backgroundMuted: "#D8A48F",
  //   foreground: "#A97155",
  //   foregroundMuted: "#704214",
  //   textColor: "#4B3621",
  //   accentColor: "#704214",
  // },
  // "midnight plum": {
  //   background: "#2E1A47",
  //   backgroundMuted: "#43255B",
  //   foreground: "#6B3FA0",
  //   foregroundMuted: "#A084CA",
  //   textColor: "#E0D4F7",
  //   accentColor: "#A084CA",
  // },
  // "soft lavender": {
  //   background: "#F3E5F5",
  //   backgroundMuted: "#E1BEE7",
  //   foreground: "#CE93D8",
  //   foregroundMuted: "#8E24AA",
  //   textColor: "#4A0072",
  //   accentColor: "#8E24AA",
  // },
  // "amber woods": {
  //   background: "#4B3832",
  //   backgroundMuted: "#6E4B3A",
  //   foreground: "#9E6B4B",
  //   foregroundMuted: "#D9B08C",
  //   textColor: "#FFE6C7",
  //   accentColor: "#D9B08C",
  // },
  // "dawn mist": {
  //   background: "#E8F0F2",
  //   backgroundMuted: "#D9E4EC",
  //   foreground: "#BCCCDC",
  //   foregroundMuted: "#9FB3C8",
  //   textColor: "#3E4C59",
  //   accentColor: "#9FB3C8",
  // },
  // "golden sands": {
  //   background: "#FAF3DD",
  //   backgroundMuted: "#FFE5B4",
  //   foreground: "#FFD580",
  //   foregroundMuted: "#FFC300",
  //   textColor: "#5C4400",
  //   accentColor: "#FFC300",
  // },
  // "charcoal night": {
  //   background: "#2C2C2C",
  //   backgroundMuted: "#3D3D3D",
  //   foreground: "#5A5A5A",
  //   foregroundMuted: "#A0A0A0",
  //   textColor: "#FFFFFF",
  //   accentColor: "#A0A0A0",
  // },
  // "icy mint": {
  //   background: "#E0FFF9",
  //   backgroundMuted: "#C2F0E8",
  //   foreground: "#A0E7D7",
  //   foregroundMuted: "#59C3C3",
  //   textColor: "#0A5353",
  //   accentColor: "#59C3C3",
  // },
  // "citrus burst": {
  //   background: "#FFF4E0",
  //   backgroundMuted: "#FFE0B2",
  //   foreground: "#FFB74D",
  //   foregroundMuted: "#FF9800",
  //   textColor: "#5C3700",
  //   accentColor: "#FF9800",
  // },
  // "twilight sky": {
  //   background: "#3A0CA3",
  //   backgroundMuted: "#5F0F40",
  //   foreground: "#9D4EDD",
  //   foregroundMuted: "#F72585",
  //   textColor: "#FFFFFF",
  //   accentColor: "#F72585",
  // },
  // evergreen: {
  //   background: "#014421",
  //   backgroundMuted: "#1B5E20",
  //   foreground: "#388E3C",
  //   foregroundMuted: "#81C784",
  //   textColor: "#E8F5E9",
  //   accentColor: "#81C784",
  // },
  // "storm grey": {
  //   background: "#2E2E2E",
  //   backgroundMuted: "#424242",
  //   foreground: "#616161",
  //   foregroundMuted: "#BDBDBD",
  //   textColor: "#E0E0E0",
  //   accentColor: "#BDBDBD",
  // },
  // "coral reef": {
  //   background: "#FF7F50",
  //   backgroundMuted: "#FFAD87",
  //   foreground: "#FFA07A",
  //   foregroundMuted: "#FF6347",
  //   textColor: "#4A1C17",
  //   accentColor: "#FF6347",
  // },
  // "blush rose": {
  //   background: "#FFE4E1",
  //   backgroundMuted: "#FFD1DC",
  //   foreground: "#FFB6B9",
  //   foregroundMuted: "#FF6F91",
  //   textColor: "#4B1C1C",
  //   accentColor: "#FF6F91",
  // },
  // "mocha mist": {
  //   background: "#BFA6A0",
  //   backgroundMuted: "#A1887F",
  //   foreground: "#8D6E63",
  //   foregroundMuted: "#5D4037",
  //   textColor: "#3E2723",
  //   accentColor: "#5D4037",
  // },
  // "spring bloom": {
  //   background: "#C1F0F6",
  //   backgroundMuted: "#AEE1E6",
  //   foreground: "#87C4CF",
  //   foregroundMuted: "#47A8BD",
  //   textColor: "#055A6C",
  //   accentColor: "#47A8BD",
  // },
  // "neon noir": {
  //   background: "#0F0F0F",
  //   backgroundMuted: "#1A1A1A",
  //   foreground: "#39FF14",
  //   foregroundMuted: "#00FF9F",
  //   textColor: "#FFFFFF",
  //   accentColor: "#00FF9F",
  // },
};

export const toastErrorStyles = {
  background: "#ba181b",
  borderColor: "#e5383b",
  color: "white",
};

export const toastSuccessStyles = {
  background: "#208b3a",
  borderColor: "#2dc653",
  color: "white",
};
